# circleci config

jobs:
  build:
    - run: |
        bazel run @graknlabs_grabl//correctness:start -- --test test-A --org $CIRCLE_ORG --repo $CIRCLE_REPO --job-id $CIRCLE_JOB_ID
        bazel build //...
        bazel run @graknlabs_grabl//correctness:success -- --test test-A --org $CIRCLE_ORG --repo $CIRCLE_REPO --job-id $CIRCLE_JOB_ID
  performance-small:
    run: |
      bazel test //test/performance:small--
        --grakn-address $GRABL_GRAKN_ADDRESS
        --org $GRABL_ORG
        --repo $GRABL_REPO
        --commit $GRABL_COMMIT
        --username $GRABL_USERNAME
        --token $GRABL_TOKEN
  deploy-github:
    - run: echo "deploy github"
  grabl-correctness-completed:
    run: |
      bazel run @graknlabs_grabl//correctness:completed -- --org $CIRCLE_ORG --repo $CIRCLE_REPO
  grabl-release-completed:
    run: |
      bazel run @graknlabs_grabl//release:completed -- --org $CIRCLE_ORG --repo $CIRCLE_REPO

workflows:
  grakn:
    jobs:
      - build
      - performance-small:
          requires:
            - build
      - grabl-correctness-completed:
          requires:
            - build

  grakn-release-branch:
    jobs:
      - deploy-github
      - grabl-release-completed:
          requires:
            - deploy-github