# grabl config
# @graknlabs_grakn_core

config:
  version-candidate: ./VERSION
  dependencies:
    - graql: [snapshot, release]
    - protocol: [snapshot, release]
    - client-java: release

sync:
  validation:
    jobs:
      sync-validate-compilation:
        machine: ubuntu-19.10
        type: foreground
        script: |
          sudo apt update -y
          sudo apt install -y openjdk-8-jdk pkg-config zip g++ zlib1g-dev unzip python
          curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
          bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh && hash -r
          git clone https://github.com/graknlabs/grakn.git
          cd grakn
          bazel run @graknlabs_build_tools//sync-dependencies-bazel $GRABL_DEPENDENCIES_NEW         # graql@abc123 protocol@bcd234
          bazel build //...
      # sync-validate-correctness:
      #   machine: ubuntu-19.10
      #   type: foreground
      #   script: |
      #     sudo apt update -y
      #     sudo apt install -y openjdk-8-jdk pkg-config zip g++ zlib1g-dev unzip python
      #     curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
      #     bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh && hash -r
      #     git clone https://github.com/graknlabs/grakn.git
      #     cd grakn
      #     bazel run @graknlabs_build_tools//sync-dependencies-bazel $GRABL_DEPENDENCIES_NEW         # graql@abc123 protocol@bcd234
      #     bazel build //test/basic-correctness
    execution:
      - sync-validate-compilation
      # - sync-validate-correctness
  update:
    job:
      machine: ubuntu-19.10
      type: foreground
      script: |
        sudo apt update -y
        sudo apt install -y openjdk-8-jdk pkg-config zip g++ zlib1g-dev unzip python
        curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
        bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh && hash -r
        git clone https://github.com/graknlabs/grakn.git
        cd grakn
        bazel run @graknlabs_build_tools//sync-dependencies-bazel $GRABL_DEPENDENCIES_NEW         # graql@abc123 protocol@bcd234
        bazel run @graknlabs_build_tools//sync-dependencies-npm $GRABL_DEPENDENCIES_NEW           # graql@abc123 protocol@bcd234
        # Committing and pushing to the upstream repo should be done by Grabl
build:
  static-analysis:
    job:
      dependency-analysis:
        machine: ubuntu-19.10
        type: foreground
        script: |
          sudo apt update -y
          sudo apt install -y openjdk-8-jdk pkg-config zip g++ zlib1g-dev unzip python
          curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
          bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh && hash -r
          git clone https://github.com/graknlabs/grakn.git
          cd grakn
          bazel run @graknlabs_build_tools//analysis:dependency -- graql@graknlabs_graql protocol@graknlabs_protocol client-java@graknlabs_client_java
          # export $GRABL_DEPENDENCIES_STATUS="graql@123,protocol@234,client-java@345"
          # grabl.io/events/automation/graknlabs/grakn/edbea56/build/static-anlaysis/dependency -- graql@123, protocol@234, client-java@345
  correctness:
    type: external
  performance:
    jobs:
      # run-grakn:
      #   machine: ubuntu-19.10
      #   type: background
      #   timeout: "1800"
      #   script: |
      #     sudo apt update -y
      #     sudo apt install -y openjdk-8-jdk pkg-config zip g++ zlib1g-dev unzip python
      #     curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
      #     bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh && hash -r
      #     git clone https://github.com/graknlabs/grakn.git
      #     cd grakn
      #     bazel build //:assemble-linux-targz
      #     mkdir dist
      #     tar -xf ./bazel-bin/grakn-core-all-linux.tar.gz -C ./dist/
      #     cd ./dist/grakn-core-all-linux/
      #     ./grakn server start
      test-performance-big:
        machine: ubuntu-19.10
        type: foreground
        script: |
          sudo apt update -y
          sudo apt install -y openjdk-8-jdk pkg-config zip g++ zlib1g-dev unzip python
          curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
          bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh && hash -r
          git clone https://github.com/graknlabs/grakn.git
          cd grakn
          bazel test @graknlabs_simulation//:run --
            --grakn-address $GRABL_PERFORMANCE_RUN_GRAKN_ADDRESS
            --org $GRABL_ORG
            --repo $GRABL_REPO
            --commit $GRABL_COMMIT
            --username $GRABL_USERNAME
            --token $GRABL_TOKEN
            --iterations 50
    execution:
      # - run-grakn
      - test-performance-big
          # depends: [run-grakn]

release:
  validation:
    job:
      machine: ubuntu-19.10
      type: foreground
      script: |
        bazel run @graknlabs_build_tools//ci:release-validate-deps -- graknlabs_common graknlabs_graql graknlabs_protocol
  deployment:
    jobs:
    execution:
  bump:
    job:
      machine: ubuntu-19.10
      type: foreground
      script: bazel run @graknlabs_build_tools//ci:version-bump