build:
  performance:
    jobs:
      run-grakn:
        machine: grabl-ubuntu-1910
        type: background
        timeout: "1800"
        script: |
          git clone https://github.com/graknlabs/grakn.git
          cd grakn
          bazel build //:assemble-linux-targz
          mkdir dist
          tar -xf ./bazel-bin/grakn-core-all-linux.tar.gz -C ./dist/
          cd ./dist/grakn-core-all-linux/
          ./grakn server start
          export GRABL_PERFORMANCE_RUN_GRAKN_URI="${HOSTNAME}:48555"
      test-performance-big:
        machine: grabl-ubuntu-1910
        type: foreground
        script: |
          git clone https://github.com/graknlabs/grakn.git
          cd grakn
          bazel run @graknlabs_simulation//:simulation -- \
            --keyspace simulation \
            --grakn-uri $GRABL_PERFORMANCE_RUN_GRAKN_URI \
            --tracing-uri $GRABL_URI \
            --org $GRABL_OWNER \
            --repo $GRABL_REPO \
            --commit $GRABL_COMMIT \
            --username $GRABL_OWNER \
            --api-token $GRABL_TOKEN \
            --iterations 50 \
            --seed 1
    execution:
      - run-grakn
      - test-performance-big:
          depends: [run-grakn]
