# grabl config
# @graknlabs_grakn_core

dependency:
  config:
    dependencies:
      - graql:
          org: graknlabs
          repo: graql
          type: [snapshot, release]
      - protocol:
          org: graknlabs
          repo: common
          type: [snapshot, release]
      - client-java:
          org: graknlabs
          repo: client-java
          type: release
  validate:
    jobs:
      dependency-validate-build:
        machine: ubuntu-19.10
        type: foreground
        run: |
          bazel run @graknlabs_build_tools//sync-dependencies-bazel $GRABL_NEW_DEPENDENCIES         # graql@abc123 protocol@bcd234
          bazel build //...
      dependency-validate-correctness:
        machine: ubuntu-19.10
          type: foreground
          run: |
            bazel run @graknlabs_build_tools//sync-dependencies-bazel $GRABL_NEW_DEPENDENCIES         # graql@abc123 protocol@bcd234
            bazel build //test/basic-correctness
    execution:
      - depedency-validate-build
      - dependency-validate-correctness
  update:
    job:
      machine: ubuntu-19.10
      type: foreground
      run: |
        bazel run @graknlabs_build_tools//sync-dependencies-bazel $GRABL_NEW_DEPENDENCIES         # graql@abc123 protocol@bcd234
        # Committing and pushing to the upstream repo should be done by Grabl

build:
  performance:
    jobs:
      run-grakn:
        machine: ubuntu-19.10
        type: background
        run: |
          bazel build //:grakn-core-all-linux-targz
          tar -xf ./bazel-bin/grakn-core-all-linux.targz -C ./dist/
          cd ./dist/
          ./grakn server start
      test-performance-big:
        machine: ubuntu-19.10
        type: foreground
        run: |
          bazel test //test/performance:big --
            --grakn-address $GRABL_PERFORMANCE_RUN_GRAKN_ADDRESS
            --org $GRABL_ORG
            --repo $GRABL_REPO
            --commit $GRABL_COMMIT
            --username $GRABL_USERNAME
            --token $GRABL_TOKEN
    execution:
      - run-grakn
      - test-performance-big:
          depends: run-grakn

release:
  config:
    version: ./VERSION
  validation:
    job:
      machine: ubuntu-19.10
      type: foreground
      run: |
        bazel run @graknlabs_build_tools//ci:release-validate-deps -- graknlabs_common graknlabs_graql graknlabs_client_java
  deployment:
    jobs:
    execution:
  bump:
    job:
      machine: ubuntu 19.10
      type: foreground
      run: bazel run @graknlabs_build_tools//ci:version-bump